In [16]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
import sys

AttributeError: NeuralNet instance has no attribute 'preprocess'

In [17]:
class NeuralNet:
    def __init__(self, train, activation,header = True, h1 = 4, h2 = 2):

        np.random.seed(1)
        # train refers to the training dataset
        # test refers to the testing dataset
        # h1 and h2 represent the number of nodes in 1st and 2nd hidden layers

        raw_input = pd.read_csv(train, header=None)
        # TODO: Remember to implement the preprocess method
        train_dataset = self.preprocess(raw_input)
        ncols = len(train_dataset.columns)
        nrows = len(train_dataset.index)
        self.X = train_dataset.iloc[:, 0:(ncols -1)].values.reshape(nrows, ncols-1)
        self.y = train_dataset.iloc[:, (ncols-1)].values.reshape(nrows, 1)
        self.activation = activation

        #
        # Find number of input and output layers from the dataset
        #
        input_layer_size = len(self.X[0])
        if not isinstance(self.y[0], np.ndarray):
            output_layer_size = 1
        else:
            output_layer_size = len(self.y[0])

        # assign random weights to matrices in network
        # number of weights connecting layers = (no. of nodes in previous layer) x (no. of nodes in following layer)
        self.w01 = 2 * np.random.random((input_layer_size, h1)) - 1
        self.X01 = self.X
        self.delta01 = np.zeros((input_layer_size, h1))
        self.w12 = 2 * np.random.random((h1, h2)) - 1
        self.X12 = np.zeros((len(self.X), h1))
        self.delta12 = np.zeros((h1, h2))
        self.w23 = 2 * np.random.random((h2, output_layer_size)) - 1
        self.X23 = np.zeros((len(self.X), h2))
        self.delta23 = np.zeros((h2, output_layer_size))
        self.deltaOut = np.zeros((output_layer_size, 1))

    

In [19]:
def __activation(self, x):
        activation = self.activation
        if activation == "sigmoid":
            out1 = self.__sigmoid(x)
        elif activation == "tanh":
            out1 = self.__tanh(x)
        elif activation == "ReLu":
            out1 = self.__relu(x)

        return out1

    # sigmoid function
    def __sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    # tanh function
    def __tanh(self, x):
    	return 1 - 2 / (1 + np.exp(2 * x))

    # ReLu function
    def __relu(self, x):
    	return np.maximum(0, x)

    #
    # TODO: Define the function for tanh, ReLu and their derivatives
    #
    def __activation_derivative(self, x):
        activation = self.activation
        if activation == "sigmoid":
            self.__sigmoid_derivative(x)
        elif activation == "tanh":
        	self.__tanh_derivative(x)
        elif activation == "ReLu":
        	self.__relu_derivative(x)

    # derivative of sigmoid function, indicates confidence about existing weight
    def __sigmoid_derivative(self, x):
        return x * (1 - x)

    # derivative of tanh function
    def __tanh_derivative(self, x):
    	return 1-x * x

    # derivative of ReLu function  
    # def __relu_derivative(self, x):
    #     for c in range(len(x)):
    #         for r in range(len(x[0])):
    #             if x[c][r] > 0:
    #                 x[c][r] = 1
    #             else:
    #                 x[c][r] = 0

    #     return x
    def __relu_derivative(self, x):
        return 1 / (1 + np.exp(-x))

    #
    # TODO: Write code for pre-processing the dataset, which would include standardization, normalization,
    #   categorical to numerical, etc
    # Using Label Encoding to transform categorical to numerical
    # NA data is represented by the current column mean
    # Numerical data is transformed by its mean and sd

    def preprocess(self, X):
    	oeDF = X.copy()
    	num = X.shape[0]

    	for column in X:
    		if X[column].dtype == 'object':
    			oeDF[column] = oeDF[column].astype('category').cat.codes
    		else:
    			temp = oeDF.iloc[:num-1, column].fillna(X[column].mean())
    			mean = temp.mean()
    			std = temp.std()
    			# oeDF[column] = (oeDF[column] * 10- mean)/std

    	indexedTrain = oeDF.head(X.shape[0])

        return indexedTrain

IndentationError: unindent does not match any outer indentation level (<ipython-input-19-239988d7a4a5>, line 13)

In [ ]:
    def train(self, max_iterations = 5, learning_rate = 0.1):
        for iteration in range(max_iterations):
            out = self.forward_pass(self.X)
            error = 0.5 * np.power((out - self.y), 2)
            self.backward_pass(out)
            update_layer2 = learning_rate * self.X23.T.dot(self.deltaOut)
            update_layer1 = learning_rate * self.X12.T.dot(self.delta23)
            update_input = learning_rate * self.X01.T.dot(self.delta12)

            self.w23 += update_layer2
            self.w12 += update_layer1
            self.w01 += update_input



        print("After " + str(max_iterations) + " iterations, the total error is " + str(np.sum(error)))
        print("The final weight vectors are (starting from input to output layers)")
        print("The first layer weight vectors: ")
        print(self.w01)
        print("The second layer weight vectors: ")
        print(self.w12)
        print("The third layer weight vectors: ")
        print(self.w23)

In [ ]:
def forward_pass(self, X):
        # pass our inputs through our neural network
        in1 = np.dot(X, self.w01)
        self.X12 = self.__activation(in1)
        in2 = np.dot(self.X12, self.w12)
        self.X23 = self.__activation(in2)
        in3 = np.dot(self.X23, self.w23)
        out = self.__activation(in3)
        
        return out

In [ ]:
 def backward_pass(self, out):
        # pass our inputs through our neural network
        self.compute_output_delta(out, self.activation)
        self.compute_hidden_layer2_delta(self.activation)
        self.compute_hidden_layer1_delta(self.activation)

In [ ]:
 def compute_output_delta(self, out, activation):
        if activation == "sigmoid":
            delta_output = (self.y - out) * (self.__sigmoid_derivative(out))
        elif activation == "tanh":
        	delta_output = (self.y - out) * (self.__tanh_derivative(out))
        elif activation == "ReLu":
            delta_output = (self.y - out) * (self.__relu_derivative(out))

        self.deltaOut = delta_output


In [ ]:
def compute_hidden_layer2_delta(self, activation):
        if activation == "sigmoid":
            delta_hidden_layer2 = (self.deltaOut.dot(self.w23.T)) * (self.__sigmoid_derivative(self.X23))
        elif activation == "tanh":
            delta_hidden_layer2 = (self.deltaOut.dot(self.w23.T)) * (self.__tanh_derivative(self.X23))
        elif activation == "ReLu":
            delta_hidden_layer2 = (self.deltaOut.dot(self.w23.T)) * (self.__relu_derivative(self.X23))   

        self.delta23 = delta_hidden_layer2

In [ ]:
def compute_hidden_layer1_delta(self, activation):
        if activation == "sigmoid":
            delta_hidden_layer1 = (self.delta23.dot(self.w12.T)) * (self.__sigmoid_derivative(self.X12))
        elif activation == "tanh":
            delta_hidden_layer1 = (self.delta23.dot(self.w12.T)) * (self.__tanh_derivative(self.X12))
        elif activation == "ReLu":
            delta_hidden_layer1 = (self.delta23.dot(self.w12.T)) * (self.__relu_derivative(self.X12))

        self.delta12 = delta_hidden_layer1

In [ ]:
def compute_input_layer_delta(self, activation):
        if activation == "sigmoid":
            delta_input_layer = np.multiply(self.__sigmoid_derivative(self.X01), self.delta01.dot(self.w01.T))
        elif activation == "tanh":
            delta_input_layer = np.multiply(self.__tanh_derivative(self.X01), self.delta01.dot(self.w01.T))
        elif activation == "ReLu":
            delta_input_layer = np.multiply(self.__relu_derivative(self.X01), self.delta01.dot(self.w01.T))

        self.delta01 = delta_input_layer

In [4]:

     
    
    def predict(self, test, header = True):

    	raw_test_input = pd.read_csv(test, header=None)
        # TODO: Remember to implement the preprocess method
        test_dataset = self.preprocess(raw_test_input)
        test_ncols = len(test_dataset.columns)
        test_nrows = len(test_dataset.index)

        test_Y = test_dataset.iloc[:, (test_ncols-1)].values.reshape(test_nrows, 1)
        
        test_X = test_dataset.iloc[:, 0:(test_ncols-1)].values.reshape(test_nrows, test_ncols-1)

        test_out = self.forward_pass(test_X)
        test_error = 0.5 * np.power((test_Y - test_out), 2)


        return np.sum(test_error)
    

IndentationError: unexpected indent (<ipython-input-4-188a4185e8ee>, line 2)

In [6]:
neural_network =NeuralNet("adultTrain.csv", "sigmoid")

In [7]:
neural_network.train()

After 5 iterations, the total error is 3920.5
The final weight vectors are (starting from input to output layers)
The first layer weight vectors: 
[[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.2064651   0.07763347 -0.16161097  0.370439  ]
 [-0.5910955   0.75623487 -0.94522481  0.34093502]
 [-0.1653904   0.11737966 -0.71922612 -0.60379702]
 [ 0.60148914  0.93652315 -0.37315164  0.38464523]
 [ 0.7527783   0.78921333 -0.82991158 -0.92189043]
 [-0.66033916  0.75628501 -0.80330633 -0.15778475]
 [ 0.91577906  0.06633057  0.38375423 -0.36896874]
 [ 0.37300186  0.66925134 -0.96342345  0.50028863]
 [ 0.97772217  0.49633131 -0.43911202  0.57855866]
 [-0.79354799 -0.10421295  0.81719101 -0.4127717 ]
 [-0.42444932 -0.73994286 -0.96126608  0.35767107]
 [-0.57674377 -0.46890668 -0.01685368 -0.89327491]]
The second layer weight vectors: 
[[-0.57669351 -0.64461237]
 [20.49562127 -1.33225494]
 [-0.79533114 -0.17188802]
 [20.70581051 -1.903413

In [8]:
testError = neural_network.predict("adultTest.csv")

In [10]:
print("The testError is")
print(testError)

The testError is
1923.0


In [15]:
print(self.y)

NameError: name 'self' is not defined